version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_DB: aggregator_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgre
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
